### PR TITLE
Bootstrap 5 support

### LINKED ISSUE #2832: Bootstrap 5 Plans
**Is your feature request related to a problem? Please describe.**
Bootstrap 5 has now been released and this library prevents its use.

**Describe the solution you'd like**
Bootstrap 5 to be supported.

**Describe alternatives you've considered**
I'm not convinced, but it may be possible to support both 4 and 5 in future minor release.

**Additional context**
I'm mainly interested in what the plans are as I assume there are/will be some. It will be some time yet before other libraries such as `@ng-bootstrap/ng-bootstrap` also support Bootstrap 5.

### PR DESCRIPTION
**Pull request by internalsystemerror**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Update bootstrap to v5

**What is the current behavior? (You can also link to an open issue here)**
Bootstrap v4 is used

**What is the new behavior (if this is a feature change)?**
Bootstrap v5 is used

**Please check if the PR fulfills these requirements**
- [x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] A unit test has been written for this change.
- [x] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**
N/A (visual changes should be none if possible)

**Other information**:
I had a go at implementing floating labels, however this would require the form control to be a direct sibling to the label, which I'm not sure is possible currently. Alternatively we could include the entire floating label css but rewritten (the first option would be ideal however).

Closes #2832.

### CODE REVIEW

**Comment by internalsystemerror** [comment]
I believe this is now ready for review. There is a failing test in `core` but I believe this to have already been failing before the changes involved in this PR, since this is based on the `main` branch.

**Comment by aitboudad** [comment]
:+1:, I think we need to mention the new change in our [UPGRADE](https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-6.0.md) file

**Comment by internalsystemerror** [comment]
@aitboudad Added the upgrade documentation (I left a blank space for core docs if needed) and updated the README ready for ng12.

**Comment by manuelmeister** [comment]
I think this should be done in formly v6 not v7, because v6 is currently just a pre-release.

**Comment by internalsystemerror** [comment]
Do you not want bootstrap 4 users to be able to use ng12 though? Can v5 already use Angular 12?

**Comment by aitboudad** [comment]
this feature will be added in `V6` not `V7`.

> Can v5 already use Angular 12?

it should work I think

**Comment by internalsystemerror** [comment]
I will update the PR accordingly

**Comment by internalsystemerror** [comment]
I believe this is now ready.

**Comment by Allcharles** [comment]
> this feature will be added in `V6` not `V7`.
> 
> > Can v5 already use Angular 12?
> 
> it should work I think

Has this PR been merged into a pre-release deploy for `V6` yet? Bootstrap 5 has been out for a while now and I would love to begin the process of migrating my website.

**Comment by aitboudad** [comment]
> Has this PR been merged into a pre-release deploy for V6 yet?

it'll be included in our next alpha

**Comment by aitboudad** [comment]
Thank you @internalsystemerror!

**Comment by Wanchai** [comment]
Hi, thanks for your great work!

We need a new release of version6 to support Bootstrap 5.

Thanks in advance!

**Comment by aitboudad** [comment]
I'll make sure to make a new release this week which include this feature

**Comment by aitboudad** [comment]
Bootstrap 5 support is released in https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.4, we'll switch into beta release within 1/2 weeks.

**Pull request merged**
