### PR TITLE
feat(primeng): calendar support

### PR DESCRIPTION
**Pull request by vstiebe**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add PrimeNG calendar support.

**What is the current behavior? (You can also link to an open issue here)**
There is no default PrimeNG calendar support or demo.

**What is the new behavior (if this is a feature change)?**
There is a default PrimeNG calendar support and demo.

**Please check if the PR fulfills these requirements**
- [x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] A unit test has been written for this change.
- [x] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

### CODE REVIEW

**Comment by aitboudad** [comment]
Could you please add some basic tests (check the existing ones), thanks!

**Comment by vstiebe** [comment]
Will do.

**Comment by vstiebe** [comment]
@aitboudad About the `npm run format` error.
After running `npm run format:fix` and `npm run test` it looks like the build issue is solved without breaking any tests.

Should I post a new pull request with the `npm run format:fix` result? 
Or are you already reviewing the prettier results?

**Comment by aitboudad** [comment]
just push it here, it should be applied only to the changes files unless you've updated deps!

**Review by aitboudad — APPROVED** [review]

**Comment by aitboudad** [comment]
Thank you @vstiebe!

**Pull request merged**
