### PR TITLE
feat(ng-zorro-antd): add ui-ng-zorro-antd

### PR DESCRIPTION
**Pull request by wenqi73**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature, ref #1365 

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**
add ng-zorro-antd ui

**Please check if the PR fulfills these requirements**
- [x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] A unit test has been written for this change.
- [x] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

### CODE REVIEW

**Comment by aitboudad** [comment]
Hi, thanks for the PR, I'll check this once working on `V6`.

**Comment by aitboudad** [comment]
merged in #1951.
Thank you @wenqi73!

**Comment by aitboudad** [comment]
*Note*: published an early version `0.0.1` for `@ngx-formly/ng-zorro-antd` which you can use with `v5`, a stable version is expected in `formly@v6`.

Happy coding!

**Comment by zzhimin** [comment]
you can also use this library（More diverse configuration options）：https://github.com/zzhimin/ngx-ng-zorro-formly

**Pull request closed without merging**
