### PR TITLE
feat(core): support validations for fieldGroup with empty key

### LINKED ISSUE #1476: JSON powered with validation
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Attempting to have a JSON powered form with validation

**Expected behavior**
Be able to load form field and defined validation from JSON

**Minimal reproduction of the problem with instructions**
Refer to this simplified example:
https://stackblitz.com/edit/angular-oqnqnw
I have added a validator to the first name +last name fields to prevent entry of John Doe.
In reality I will have 30+ fields and need to have validation between various fields on the form.

I'm assuming the way to do this is by then have a fieldGroup for those fields (in this case the whole form) so that i can access the appropriate field values (if there's a better way to do this happy to hear about it)
In the example the nameVal function will do the validation of the field values and provide error feedback.

The issue is due to adding the fieldGroup to the form fields - this appears to prevent the JSON data from being loaded into the fields. If i maps the fields to the fieldGroup it loads the data but the event then doesn't fire to perform validation.

`
```
// This is required to perform validation but prevents data loading from json
      this.fields = fields.map(f => {
        if (f.templateOptions && f.templateOptions.change) {
          f.templateOptions.change = Function('$event', f.templateOptions.change).bind(this);
        }
return f;
      });`
```
```

      // This is required to load the data but then validation isn't called

      this.fields = fields[0].fieldGroup;
```

**What is the motivation / use case for changing the behavior?**
I'd like to have JSON powered forms with some complex validation between multiple fields on a form.

Thanks.

### PR DESCRIPTION
**Pull request by aitboudad**
fix #1476

### CODE REVIEW

**Comment by kenisteward** [comment]
Thank you for this pr!!

**Comment by AparnaNallamalli** [comment]
lifecycle: {
        onInit: (form, field) => {
          
          field.formControl.valueChanges
        
          .pipe(
            takeUntil(this.onDestroy$),
            tap(() => {
              
I need only for formcontrol value but it is taking valuechanges, please help me how to resolve this

**Comment by aitboudad** [comment]
@AparnaNallamalli to get the form control value:

```ts
field.formControl.value
```

**Comment by aitboudad** [comment]
**Note**: This feature has been ported to [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0).

**Pull request merged**
