### PR TITLE
feat(kendo): add primitive option in props

### PR DESCRIPTION
**Pull request by luizfbicalho**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
kendo template has fixed value in primitive, if you need to pass an object on the value it makes an error 

**What is the current behavior? (You can also link to an open issue here)**
#3529 

**What is the new behavior (if this is a feature change)?**
there will be a primitive prop value on kendo select props

**Please check if the PR fulfills these requirements**
- [X ] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] A unit test has been written for this change.
- [X ] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [X ] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

### CODE REVIEW

**Comment by luizfbicalho** [comment]
@aitboudad  what's the impact of this change?

**Comment by aitboudad** [comment]
@luizfbicalho I'll merge it soon, just need some time to test it on my side.

**Comment by luizfbicalho** [comment]
Hey @aitboudad  Is this dead?

**Comment by aitboudad** [comment]
Thank you @luizfbicalho!

**Pull request merged**
