### PR TITLE
Add any of support

### PR DESCRIPTION
**Pull request by logvinoleg89**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feature

**What is the current behavior? (You can also link to an open issue here)**
Issue https://github.com/ngx-formly/ngx-formly/issues/1459. If the json-schema includes `anyOf` and `oneOf` constructions, all of these constructions get processed as `oneOf`.

**What is the new behavior (if this is a feature change)?**
`oneOf` and `anyOf` constructions get processed differently. The dropdown control with multiple selection is used to choose `anyOf` options.

**Please check if the PR fulfills these requirements**
- [x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] A unit test has been written for this change.
- [x] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**
Screenshot 2019-10-22 at 11 34 25
Screenshot 2019-10-22 at 11 35 37
Screenshot 2019-10-22 at 11 35 14

**Other information**:
I’d like to use `ngx-fornly` to generate forms based on json-schemas. `oneOf`/`anyOf` constructions support is critical for me. I’ve considered the implementation of this functionality in `ngx-formly@5.5.1` and found out that, in fact, only `oneOf` logic works correctly. To support `anyOf`, I’ve made certain changes, which allow to display the dropdown control with multiple selection. It allows to display form controls of several `anyOf` array items simultaneously.

### CODE REVIEW

**Comment by aitboudad** [comment]
I think that's the correct behavior, I'll check the code later.
@kenisteward could you please confirm it 🙏?

**Comment by kenisteward** [comment]
https://json-schema.org/understanding-json-schema/reference/combining.html#anyof

@aitboudad semantically this is how it works.  The object should be able to validate against any (one or more) of the schemas.  How we want to display this and errors in the UI is what we need to consider.

Having the default generate a list that will allow you as a user to decide which fields go in is fine, but we could also just generate all the fields and allow them to fill out whichever best suits them.  Having a construct to constrict which ones we want to generate would be helpful too.

**Comment by aitboudad** [comment]
@kenisteward many thanks!
we'll stick with the above proposal to make it consistent with `oneOf` implementation.

@logvinoleg89 I'm going to consider this as bug fix which will be merged and released in `5.5.2` version.

**Comment by aitboudad** [comment]
close in favor of #1873.

**Comment by aitboudad** [comment]
[v5.5.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.2) is released which includes a fix for this issue!

**Pull request closed without merging**
