### PR TITLE
Update kendo peer dependencies

### PR DESCRIPTION
**Pull request by luizfbicalho**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
this makes any available version of kendo ui compatible for the library

What is the current behavior? (You can also link to an open issue here)
https://github.com/ngx-formly/ngx-formly/issues/3571

What is the new behavior (if this is a feature change)?
any version of kendo above the minimum will be accepted

Please check if the PR fulfills these requirements

 The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
 A unit test has been written for this change.
 Running npm run build produced a successful build. (Unit testing can be done by running npm test;)
 My code has been linted. (npm run lint to do this. npm run build will fail if there are files not linted.)
Please provide a screenshot of this feature before and after your code changes, if applicable.

Other information:

### CODE REVIEW

**Comment by luizfbicalho** [comment]
Added my controls to this version @aitboudad 

Grid
Treegrid
HtmlEditor
MultiSelect
Combobox

**Comment by luizfbicalho** [comment]
Hi @aitboudad  Is there any  way I can speed this up?

**Comment by aueelis** [comment]
I'm watching this closely as we are also relying on this update and I thank you for your contributions to try to fix this.

However, I must say that I would simply ignore your PR if this was my repository:
- Your PR has 9 commits out of which only 5 are related to the topic.
- The 5 related commits should be squashed into a single commit.
- You are failing the CI build.
 
What do you expect?

**Comment by luizfbicalho** [comment]
> I'm watching this closely as we are also relying on this update and I thank you for your contributions to try to fix this.
> 
> However, I must say that I would simply ignore your PR if this was my repository:
> 
> * Your PR has 9 commits out of which only 5 are related to the topic.
> * The 5 related commits should be squashed into a single commit.
> * You are failing the CI build.
> 
> What do you expect?

I'm not sure why the CI is failing, I build it perfectly in my machine

**Comment by aueelis** [comment]
You can see the reason by inspecting the failing build step. This build is simply failing because your commits don't conform to the `commitlint` configuration. A possible correct commit message would probably be

> fix(kendo): update peer dependencies

**Comment by luizfbicalho** [comment]
Ok, I'll stop this and make a new one only with the dependencies

**Comment by aitboudad** [comment]
**Note**:  In order to keep our code base maintainable, we give additional types a low priority so in case you want to make them available asap I'd suggest to create your own package instead.

**Pull request closed without merging**
