### PR TITLE
feat(core): add preset module to enable form config re-use

### PR DESCRIPTION
**Pull request by MaxKless**
#3208

**Please check if the PR fulfills these requirements**
- [x] The commit messages follow our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] A unit test has been written for this change.
- [x] Running `npm run build` produced a successful build. (Unit testing can be done by running `npm test`;)
- [x] My code has been linted. (`npm run lint` to do this. `npm run build` will fail if there are files not linted.)

**Please provide a screenshot of this feature before and after your code changes, if applicable.**

**Other information**:

### CODE REVIEW

**Comment by MaxKless** [comment]
Hi @aitboudad, I think this feature is pretty done. 
I managed without an extra service, every thing is done in the extension and the formly config service.

I added a guide and an example as well as tests.
I have another PR in the pipeline where I make some changes and add more tests but it's kind of out of scope for this PR.

**Comment by aitboudad** [comment]
> What do you think? :)

Looks good at the first sight, will check it further at the end of week and making a merge.
Thank you!

**Comment by aitboudad** [comment]
> What do you think? :)

Looks good at the first sight, will check it further at the end of week and making a merge.
Thank you!

**Comment by MaxKless** [comment]
@aitboudad any updates?

**Comment by aitboudad** [comment]
Sorry due to lack of time 🙏, will try to force myself to check it late this week.

**Comment by MaxKless** [comment]
No don't worry, take your time. I just wanted to check in. Thank you so much for all the time you spend on formly 🙏 🙏

**Comment by aitboudad** [comment]
Thank you @MaxKless!

**Pull request merged**
